from turtle import *
from random import *
speed(0)
def khamir(x):
    up()
    goto(0,-x)
    color('#b88b23')
    down()
    begin_fill()
    circle(x)
    end_fill()
def gharche(a,b):
    up()
    color('#854a10')
    goto(a,b)
    begin_fill()
    lt(randint(1,364))
    circle(30,180)
    circle(15,180)
    lt(150)
    fd(30)
    lt(120)
    fd(30)
    lt(120)
    fd(30)
    lt(150)
    circle(15,180)
    end_fill()
    goto(a,b)
    down()
    pensize(3)
    color('black')
    circle(30,180)
    circle(15,180)
    lt(150)
    fd(30)
    lt(120)
    fd(30)
    lt(120)
    fd(30)
    lt(150)
    circle(15,180)
    up()
def panir(h,j):
    up()
    goto(h,j)
    down()
    color('#e6dfd8')
    begin_fill()
    for i in range(4):
        fd(3)
        lt(90)
    end_fill()
    up()
def peperon(k,l):
    up()
    goto(k,l)
    color('#851121')
    begin_fill()
    circle(50)
    end_fill()
    pensize(7)
    color('#5e0915')
    down()
    circle(50)
    up()
def finish(x):
    up()
    color('#6b4d07')
    pensize(5)
    home()
    down()
    goto(0,x)
    goto(0,0)
    goto(-x,0)
    goto(x,0)
    goto(0,0)
    lt(45)
    fd(x)
    bk(x*2)
    goto(0,0)
    rt(90)
    fd(x)
    bk(x*2) 
    home()
    goto(0,-x)
    pensize(15)
    down()
    circle(x)
    up()
    goto(-x-10,x+10)
    down()
    color('Black')
    pensize(10)
    for i in range(4):
        fd((x+10)*2)
        rt(90)
    up()
    goto(-x-10,x+10)
    down()
    rt(225)
    fd(x+50)
    lt(135)
    fd((x+10)*2)
    lt(45)
    fd(x+50)
    lt(45)
    up()
    goto(-x-10,x+10)
    color('#962334')
    begin_fill()
    rt(225)
    fd(x+50)
    lt(135)
    fd((x+10)*2)
    lt(45)
    fd(x+50)
    end_fill()
input('Khshe oomadi be pizza froshi haje Pouya! ')
g = int(input('ghotro biza ro bego--> '))
khamir(g)

p = input('panir cheghadre mikhay?(kam,ziad,kheily ziad)--> ')
if p == 'kam':
    for i in range(30):
        panir(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
elif p == 'ziad':
    for i in range(50):
        panir(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
else:
    for i in range(100):
        panir(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))

o = input('gharche mikhay?(are,na)--> ')
if o == 'are':
    for i in range(int(input('chanta?'))):
        gharche(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
else:
    print('ok')
pe = input('peperoni cheghadre mikhay?(kam,ziad,kheily ziad)--> ')
if p == 'kam':
    for i in range(30):
        peperon(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
elif p == 'ziad':
    for i in range(50):
        peperon(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
else:
    for i in range(100):
        peperon(randint(-1*(g//2),g//2),randint(-1*(g//2),g//2))
finish(g)
mainloop()